### ISSUE TITLE
  File "unwrap.py", line 296, in <module>

### ISSUE THREAD

**Issue by bobbyjayblack** [Nepherhotep/unwrap_labels#1]
Hello Alexey, I receive the following errors when trying to run your script.
I am running Ubuntu 18.04.1 with OpenCV 4.0.1. Below is my pip freeze'

```bash
(OpenCV-4.0.1-py3) robot@ubuntu:~/test/alex/unwrap_labels-master$ ls
image.jpg  README.md  samples  trig_utils.py  unwrap.py
(OpenCV-4.0.1-py3) robot@ubuntu:~/test/alex/unwrap_labels-master$ python unwrap.py 
Traceback (most recent call last):
  File "unwrap.py", line 296, in <module>
    unwrapper = LabelUnwrapper(src_image=imcv, percent_points=points)
  File "unwrap.py", line 42, in __init__
    self.width = self.src_image.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'
(OpenCV-4.0.1-py3) robot@ubuntu:~/test/alex/unwrap_labels-master$ python unwrap.py image.jpg 
Traceback (most recent call last):
  File "unwrap.py", line 296, in <module>
    unwrapper = LabelUnwrapper(src_image=imcv, percent_points=points)
  File "unwrap.py", line 42, in __init__
    self.width = self.src_image.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'
(OpenCV-4.0.1-py3) robot@ubuntu:~/test/alex/unwrap_labels-master$ 
```

```bash
(OpenCV-4.0.1-py3) robot@ubuntu:~/test/alex/unwrap_labels-master$ pip freeze
backcall==0.1.0
Click==7.0
cloudpickle==0.7.0
cycler==0.10.0
dask==1.1.0
decorator==4.3.2
dlib==19.16.0
face-recognition==1.2.3
face-recognition-models==0.3.0
imutils==0.5.2
ipython==7.2.0
ipython-genutils==0.2.0
jedi==0.13.2
kiwisolver==1.0.1
matplotlib==3.0.2
networkx==2.2
numpy==1.16.0
parso==0.3.2
pexpect==4.6.0
pickleshare==0.7.5
Pillow==5.4.1
pkg-resources==0.0.0
prompt-toolkit==2.0.7
ptyprocess==0.6.0
Pygments==2.3.1
pyparsing==2.3.1
python-dateutil==2.7.5
PyWavelets==1.0.1
scikit-image==0.14.2
scikit-learn==0.20.2
scipy==1.2.0
six==1.12.0
toolz==0.9.0
traitlets==4.3.2
wcwidth==0.1.7
(OpenCV-4.0.1-py3) robot@ubuntu:~/test/alex/unwrap_labels-master$ 
```

**Comment by Nepherhotep** [comment]
The source image is empty, please make sure you have it on file system. Please also take into account that code under if __name__ == '__main__': is just for demo (not the "official" way to run the script).
