### ISSUE TITLE
the function "load_points" does not work as it should.

### ISSUE THREAD

**Issue by VtlNmnk** [Nepherhotep/unwrap_labels#3]
I copied the project into a new virtual environment,
did **pip install -r requirements.txt**, 
and after running unwrap_labels.py got this error

Traceback (most recent call last):
  File "/home/user/PycharmProjects/unwrap_labels/unwrap_labels.py", line 391, in <module>
    unwrapper = LabelUnwrapper(src_image=imcv, percent_points=points)
  File "/home/user/PycharmProjects/unwrap_labels/unwrap_labels.py", line 104, in __init__
    self.load_points()
  File "/home/user/PycharmProjects/unwrap_labels/unwrap_labels.py", line 116, in load_points
    self.point_d, self.point_e, self.point_f) = self.points
ValueError: not enough values to unpack (expected 6, got 0)

If I change in line 107  "if self.points is None:" to "if len(self.points) ==0:", еhen everything goes ok.

**Comment by Nepherhotep** [comment]
Thanks for finding the issue!
The error was introduced a couple weeks ago. I rolled back the recent commit and reuploaded version to PYPI.
Thanks!
